# Generated by Django 5.2.8 on 2025-11-20 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDB',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_Categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Categoría DB',
                'verbose_name_plural': 'Categorías DB',
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteExistente',
            fields=[
                ('id_cliente', models.AutoField(db_column='ID_Cliente', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=100)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=100)),
                ('razon_social', models.CharField(blank=True, db_column='Razon_Social', max_length=255, null=True)),
                ('ruc_ci', models.CharField(db_column='Ruc_CI', max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='Ciudad', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('limite_credito', models.DecimalField(blank=True, db_column='Limite_Credito', decimal_places=2, max_digits=12, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='Fecha_Registro')),
            ],
            options={
                'verbose_name': 'Cliente Existente',
                'verbose_name_plural': 'Clientes Existentes',
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(db_column='ID_Empleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('usuario', models.CharField(db_column='Usuario', max_length=50, unique=True)),
                ('contrasena_hash', models.CharField(db_column='Contrasena_Hash', max_length=60)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='Fecha_Ingreso')),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='Ciudad', max_length=100, null=True)),
                ('pais', models.CharField(blank=True, db_column='Pais', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, db_column='Fecha_Baja', null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id_hijo', models.AutoField(db_column='ID_Hijo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Hijo',
                'verbose_name_plural': 'Hijos',
                'db_table': 'hijos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id_impuesto', models.AutoField(db_column='ID_Impuesto', primary_key=True, serialize=False)),
                ('nombre_impuesto', models.CharField(db_column='Nombre_Impuesto', max_length=50, unique=True)),
                ('porcentaje', models.DecimalField(db_column='Porcentaje', decimal_places=2, max_digits=4)),
                ('vigente_desde', models.DateField(db_column='Vigente_Desde')),
                ('vigente_hasta', models.DateField(blank=True, db_column='Vigente_Hasta', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'impuestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id_lista', models.AutoField(db_column='ID_Lista', primary_key=True, serialize=False)),
                ('nombre_lista', models.CharField(db_column='Nombre_Lista', max_length=100, unique=True)),
                ('fecha_vigencia', models.DateField(blank=True, db_column='Fecha_Vigencia', null=True)),
                ('moneda', models.CharField(db_column='Moneda', default='PYG', max_length=3)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'db_table': 'listas_precios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoExistente',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_Producto', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('stock_minimo', models.DecimalField(blank=True, db_column='Stock_Minimo', decimal_places=3, max_digits=10, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_Creacion')),
            ],
            options={
                'verbose_name': 'Producto Existente',
                'verbose_name_plural': 'Productos Existentes',
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedorDB',
            fields=[
                ('id_proveedor', models.AutoField(db_column='ID_Proveedor', primary_key=True, serialize=False)),
                ('ruc', models.CharField(db_column='RUC', max_length=20, unique=True)),
                ('razon_social', models.CharField(db_column='Razon_Social', max_length=255)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='Ciudad', max_length=100, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='Fecha_Registro')),
            ],
            options={
                'verbose_name': 'Proveedor DB',
                'verbose_name_plural': 'Proveedores DB',
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('nro_tarjeta', models.CharField(db_column='Nro_Tarjeta', max_length=20, primary_key=True, serialize=False)),
                ('saldo_actual', models.BigIntegerField(db_column='Saldo_Actual', default=0)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Bloqueada', 'Bloqueada'), ('Vencida', 'Vencida')], db_column='Estado', default='Activa', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='Fecha_Vencimiento', null=True)),
                ('saldo_alerta', models.DecimalField(blank=True, db_column='Saldo_Alerta', decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_Creacion')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id_tipo_cliente', models.AutoField(db_column='ID_Tipo_Cliente', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(db_column='Nombre_Tipo', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Cliente',
                'db_table': 'tipos_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRolGeneral',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_Rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='Nombre_Rol', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'tipos_rol_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad', models.AutoField(db_column='ID_Unidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('abreviatura', models.CharField(db_column='Abreviatura', max_length=10)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidades_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaSaldoClientes',
            fields=[
                ('id_cliente', models.IntegerField(db_column='ID_Cliente', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_column='Nombre_Completo', max_length=201)),
                ('saldo', models.BigIntegerField(db_column='Saldo')),
            ],
            options={
                'verbose_name': 'Saldo de Cliente',
                'verbose_name_plural': 'Saldos de Clientes',
                'db_table': 'v_saldo_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaStockAlerta',
            fields=[
                ('id_producto', models.IntegerField(db_column='ID_Producto', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Codigo', max_length=50)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('stock_actual', models.DecimalField(db_column='Stock_Actual', decimal_places=3, max_digits=10)),
                ('stock_minimo', models.DecimalField(db_column='Stock_Minimo', decimal_places=3, max_digits=10)),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'db_table': 'v_stock_alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('personal', 'Personal'), ('externo', 'Externo')], default='estudiante', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('credito_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='StockUnico',
            fields=[
                ('id_producto', models.OneToOneField(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='gestion.Producto')),
                ('stock_actual', models.DecimalField(db_column='Stock_Actual', decimal_places=3, max_digits=10)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, db_column='Fecha_Ultima_Actualizacion')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock de Productos',
                'db_table': 'stock_unico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompraProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(max_length=50, unique=True)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_realizadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='gestion.Proveedor')),
            ],
            options={
                'verbose_name': 'Compra a Proveedor',
                'verbose_name_plural': 'Compras a Proveedores',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='gestion.Categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.CompraProveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(max_length=50, unique=True)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('credito', 'Crédito'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='gestion.Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
