# Generated by Django 5.2.8 on 2025-12-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_ajustesinventario_alertassistema_auditoriacomisiones_and_more'),
    ]

    operations = [
        # Eliminación de modelos legacy (tablas ya eliminadas de la BD)
        migrations.DeleteModel(name='CtaCorriente'),
        migrations.DeleteModel(name='CtaCorrienteProv'),
        migrations.DeleteModel(name='NotasCredito'),
        
        # Los nuevos modelos ya existen en la BD, solo registramos el estado
        # No se ejecuta SQL real porque managed=False
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
