# Generated by Django 6.0 on 2025-12-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_ajustesinventario_alertassistema_auditoriacomisiones_and_more'),
    ]

    operations = [
        # Corregir foreign keys en auditoria_empleados
        migrations.RunSQL(
            "ALTER TABLE auditoria_empleados DROP FOREIGN KEY auditoria_empleados_ibfk_1;",
            reverse_sql="ALTER TABLE auditoria_empleados ADD CONSTRAINT auditoria_empleados_ibfk_1 FOREIGN KEY (ID_Empleado) REFERENCES empleados(ID_Empleado) ON DELETE CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auditoria_empleados MODIFY COLUMN ID_Empleado INT NULL;",
            reverse_sql="ALTER TABLE auditoria_empleados MODIFY COLUMN ID_Empleado INT NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auditoria_empleados ADD CONSTRAINT auditoria_empleados_ibfk_1 FOREIGN KEY (ID_Empleado) REFERENCES empleados(ID_Empleado) ON DELETE SET NULL;",
            reverse_sql="ALTER TABLE auditoria_empleados DROP FOREIGN KEY auditoria_empleados_ibfk_1;"
        ),

        # Corregir foreign keys en auditoria_usuarios_web
        migrations.RunSQL(
            "ALTER TABLE auditoria_usuarios_web DROP FOREIGN KEY auditoria_usuarios_web_ibfk_1;",
            reverse_sql="ALTER TABLE auditoria_usuarios_web ADD CONSTRAINT auditoria_usuarios_web_ibfk_1 FOREIGN KEY (ID_Cliente) REFERENCES clientes(ID_Cliente) ON DELETE CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auditoria_usuarios_web MODIFY COLUMN ID_Cliente INT NULL;",
            reverse_sql="ALTER TABLE auditoria_usuarios_web MODIFY COLUMN ID_Cliente INT NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auditoria_usuarios_web ADD CONSTRAINT auditoria_usuarios_web_ibfk_1 FOREIGN KEY (ID_Cliente) REFERENCES clientes(ID_Cliente) ON DELETE SET NULL;",
            reverse_sql="ALTER TABLE auditoria_usuarios_web DROP FOREIGN KEY auditoria_usuarios_web_ibfk_1;"
        ),

        # Corregir foreign keys en auditoria_comisiones
        migrations.RunSQL(
            "ALTER TABLE auditoria_comisiones DROP FOREIGN KEY auditoria_comisiones_ibfk_1;",
            reverse_sql="ALTER TABLE auditoria_comisiones ADD CONSTRAINT auditoria_comisiones_ibfk_1 FOREIGN KEY (ID_Tarifa) REFERENCES tarifas_comision(ID_Tarifa) ON DELETE CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auditoria_comisiones MODIFY COLUMN ID_Tarifa INT NULL;",
            reverse_sql="ALTER TABLE auditoria_comisiones MODIFY COLUMN ID_Tarifa INT NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auditoria_comisiones ADD CONSTRAINT auditoria_comisiones_ibfk_1 FOREIGN KEY (ID_Tarifa) REFERENCES tarifas_comision(ID_Tarifa) ON DELETE SET NULL;",
            reverse_sql="ALTER TABLE auditoria_comisiones DROP FOREIGN KEY auditoria_comisiones_ibfk_1;"
        ),

        # La foreign key de ID_Empleado_Modifico ya permite NULL, solo cambiar CASCADE por SET NULL
        migrations.RunSQL(
            "ALTER TABLE auditoria_comisiones DROP FOREIGN KEY auditoria_comisiones_ibfk_2;",
            reverse_sql="ALTER TABLE auditoria_comisiones ADD CONSTRAINT auditoria_comisiones_ibfk_2 FOREIGN KEY (ID_Empleado_Modifico) REFERENCES empleados(ID_Empleado) ON DELETE CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auditoria_comisiones ADD CONSTRAINT auditoria_comisiones_ibfk_2 FOREIGN KEY (ID_Empleado_Modifico) REFERENCES empleados(ID_Empleado) ON DELETE SET NULL;",
            reverse_sql="ALTER TABLE auditoria_comisiones DROP FOREIGN KEY auditoria_comisiones_ibfk_2;"
        ),
    ]
