# Generated by Django 5.2.8 on 2026-01-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_add_metrepay_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionesHijos',
            fields=[
                ('id_restriccion', models.AutoField(db_column='ID_Restriccion', primary_key=True, serialize=False)),
                ('tipo_restriccion', models.CharField(db_column='Tipo_Restriccion', help_text='Tipo: Celíaco, Intolerancia lactosa, Alergia maní, Vegetariano, etc.', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', help_text='Descripción detallada de la restricción', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', help_text='Observaciones adicionales o ingredientes específicos a evitar', null=True)),
                ('severidad', models.CharField(choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Severa', 'Severa'), ('Crítica', 'Crítica')], db_column='Severidad', default='Moderada', max_length=20)),
                ('requiere_autorizacion', models.BooleanField(db_column='Requiere_Autorizacion', default=True, help_text='Si requiere autorización para consumir productos restringidos')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='Fecha_Registro')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, db_column='Fecha_Ultima_Actualizacion')),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Restricción Alimentaria',
                'verbose_name_plural': 'Restricciones Alimentarias',
                'db_table': 'restricciones_hijos',
                'ordering': ['-severidad', 'tipo_restriccion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPortal',
            fields=[
                ('id_usuario_portal', models.AutoField(db_column='ID_Usuario_Portal', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='Email', max_length=255, unique=True)),
                ('password_hash', models.CharField(db_column='Password_Hash', max_length=255)),
                ('email_verificado', models.BooleanField(db_column='Email_Verificado', default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='Fecha_Registro')),
                ('ultimo_acceso', models.DateTimeField(blank=True, db_column='Ultimo_Acceso', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('cliente', models.OneToOneField(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_portal', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Usuario Portal',
                'verbose_name_plural': 'Usuarios Portal',
                'db_table': 'usuarios_portal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionOnline',
            fields=[
                ('id_transaccion', models.AutoField(db_column='ID_Transaccion', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('METREPAY', 'MetrePay'), ('TIGO_MONEY', 'Tigo Money'), ('TRANSFERENCIA', 'Transferencia Bancaria')], db_column='Metodo_Pago', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('CANCELADA', 'Cancelada')], db_column='Estado', default='PENDIENTE', max_length=20)),
                ('referencia_pago', models.CharField(blank=True, db_column='Referencia_Pago', max_length=255, null=True)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, db_column='Fecha_Transaccion')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, db_column='Fecha_Confirmacion', null=True)),
                ('ip_origen', models.GenericIPAddressField(db_column='IP_Origen')),
                ('detalles_json', models.TextField(blank=True, db_column='Detalles_JSON', null=True)),
                ('tarjeta', models.ForeignKey(db_column='Nro_Tarjeta', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_online', to='gestion.tarjeta')),
                ('usuario_portal', models.ForeignKey(db_column='ID_Usuario_Portal', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='gestion.usuarioportal')),
            ],
            options={
                'verbose_name': 'Transacción Online',
                'verbose_name_plural': 'Transacciones Online',
                'db_table': 'transacciones_online',
                'ordering': ['-fecha_transaccion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TokenVerificacion',
            fields=[
                ('id_token', models.AutoField(db_column='ID_Token', primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='Token', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('email_verification', 'Verificación de Email'), ('password_reset', 'Recuperación de Contraseña')], db_column='Tipo', max_length=50)),
                ('expira_en', models.DateTimeField(db_column='Expira_En')),
                ('usado', models.BooleanField(db_column='Usado', default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_Creacion')),
                ('fecha_uso', models.DateTimeField(blank=True, db_column='Fecha_Uso', null=True)),
                ('usuario_portal', models.ForeignKey(db_column='ID_Usuario_Portal', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='gestion.usuarioportal')),
            ],
            options={
                'verbose_name': 'Token de Verificación',
                'verbose_name_plural': 'Tokens de Verificación',
                'db_table': 'tokens_verificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id_preferencia', models.AutoField(db_column='ID_Preferencia', primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(db_column='Tipo_Notificacion', max_length=50)),
                ('email_activo', models.BooleanField(db_column='Email_Activo', default=True)),
                ('sms_activo', models.BooleanField(db_column='SMS_Activo', default=False)),
                ('push_activo', models.BooleanField(db_column='Push_Activo', default=False)),
                ('umbral_saldo_bajo', models.DecimalField(db_column='Umbral_Saldo_Bajo', decimal_places=2, default=5000, max_digits=10)),
                ('usuario_portal', models.OneToOneField(db_column='ID_Usuario_Portal', on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to='gestion.usuarioportal')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
                'db_table': 'preferencias_notificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(db_column='ID_Notificacion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('saldo_bajo', 'Saldo Bajo'), ('recarga_exitosa', 'Recarga Exitosa'), ('consumo_realizado', 'Consumo Realizado'), ('tarjeta_bloqueada', 'Tarjeta Bloqueada'), ('restriccion_aplicada', 'Restricción Aplicada'), ('info_general', 'Información General')], db_column='Tipo', max_length=50)),
                ('titulo', models.CharField(db_column='Titulo', max_length=255)),
                ('mensaje', models.TextField(db_column='Mensaje')),
                ('leida', models.BooleanField(db_column='Leida', default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_Creacion')),
                ('fecha_leida', models.DateTimeField(blank=True, db_column='Fecha_Leida', null=True)),
                ('usuario_portal', models.ForeignKey(db_column='ID_Usuario_Portal', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion.usuarioportal')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
