"""
Django settings for cantina_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-)!g6f^48yj^#%45t2bx6$twir*zf)dxvg7l2c535b#srsct#+c')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver', '192.168.100.10']

# CSRF Trusted Origins (para requests POST desde frontend)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.100.10:8000',
    'https://localhost:8000',
    'https://127.0.0.1:8000',
    'https://192.168.100.10:8000',
]

# Django Debug Toolbar
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
    '192.168.100.10',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'drf_spectacular',  # Documentación OpenAPI 3.0
    'django_filters',
    'corsheaders',
    'debug_toolbar',
    'django_recaptcha',
    # Local apps
    'gestion',
]

# Authentication backends
# Se usa un backend personalizado para autenticar empleados contra la tabla empleados
AUTHENTICATION_BACKENDS = [
    'gestion.backends.EmpleadoBackend',  # Backend personalizado para empleados
    'django.contrib.auth.backends.ModelBackend',  # Backend por defecto de Django
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS debe ir antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'cantina_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gestion.context_processors.rol_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'cantina_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='cantinatitadb'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Configuración para Paraguay
LANGUAGE_CODE = 'es-py'  # Español de Paraguay

TIME_ZONE = 'America/Asuncion'  # Zona horaria de Paraguay

USE_I18N = True

USE_TZ = True

# Configuración de formato regional para Paraguay
USE_L10N = True  # Usar formatos localizados

# Formatos de fecha y hora para Paraguay
DATE_FORMAT = 'd/m/Y'  # Formato: día/mes/año
DATETIME_FORMAT = 'd/m/Y H:i'  # Formato: día/mes/año hora:minuto
SHORT_DATE_FORMAT = 'd/m/Y'
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'

# Formato de números para Paraguay (separador de miles: punto, decimales: coma)
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (archivos subidos por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION
# =============================================================================

REST_FRAMEWORK = {
    # Autenticación
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # Permisos por defecto
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Paginación
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Filtros
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    # Formato de respuestas
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    # Formato de datetime
    'DATETIME_FORMAT': '%d/%m/%Y %H:%M:%S',
    'DATE_FORMAT': '%d/%m/%Y',
    'TIME_FORMAT': '%H:%M:%S',
    # Schema configurado con drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# =============================================================================
# DRF-SPECTACULAR CONFIGURATION (OpenAPI 3.0)
# =============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'Cantina Tita API',
    'DESCRIPTION': '''
    API REST completa para el Sistema de Gestión de Cantina Tita
    
    ## Funcionalidades principales:
    - 💰 **Ventas:** Gestión completa de ventas, pagos y facturación
    - 📦 **Inventario:** Control de stock, kardex y ajustes
    - 💳 **Tarjetas:** Sistema de tarjetas RFID, recargas y consumos
    - 👥 **Clientes:** Gestión de clientes, hijos y restricciones alimentarias
    - 🏫 **Almuerzos:** Sistema de almuerzos escolares y planes mensuales
    - 📊 **Reportes:** Generación de reportes PDF/Excel
    - 🔐 **Seguridad:** Autenticación JWT, 2FA y auditoría completa
    - 🎯 **Promociones:** Sistema de promociones y descuentos
    
    ## Autenticación:
    Esta API utiliza **JWT (JSON Web Tokens)** para autenticación:
    
    1. **Obtener token:** POST /api/v1/auth/token/
       ```json
       {"username": "usuario", "password": "contraseña"}
       ```
    
    2. **Usar token:** Incluir en todas las peticiones:
       ```
       Authorization: Bearer {access_token}
       ```
    
    3. **Renovar token:** POST /api/v1/auth/token/refresh/
       ```json
       {"refresh": "refresh_token"}
       ```
    
    ## Códigos de Respuesta:
    - **200:** OK - Operación exitosa
    - **201:** Created - Recurso creado exitosamente
    - **400:** Bad Request - Datos inválidos
    - **401:** Unauthorized - No autenticado
    - **403:** Forbidden - No autorizado
    - **404:** Not Found - Recurso no encontrado
    - **500:** Internal Server Error - Error del servidor
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'CONTACT': {
        'name': 'Soporte Técnico Cantina Tita',
        'email': 'contacto@cantinatita.com'
    },
    'LICENSE': {
        'name': 'Propietario',
    },
    'TAGS': [
        {'name': 'Productos', 'description': 'Gestión de productos y categorías'},
        {'name': 'Ventas', 'description': 'Operaciones de ventas y facturación'},
        {'name': 'Tarjetas', 'description': 'Sistema de tarjetas RFID'},
        {'name': 'Clientes', 'description': 'Gestión de clientes y estudiantes'},
        {'name': 'Inventario', 'description': 'Control de stock y movimientos'},
        {'name': 'Almuerzos', 'description': 'Sistema de almuerzos escolares'},
        {'name': 'Reportes', 'description': 'Generación de reportes'},
        {'name': 'Portal', 'description': 'Portal de padres y consultas online'},
        {'name': 'Seguridad', 'description': 'Autenticación y auditoría'},
    ],
}

# =============================================================================
# JWT CONFIGURATION
# =============================================================================

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'cantina-tita-api',
    'JWK_URL': None,
    'LEEWAY': 0,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
}

# =============================================================================
# CORS CONFIGURATION
# =============================================================================

# Configuración de CORS para permitir requests desde apps móviles/web
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React
    "http://localhost:4200",  # Angular
    "http://localhost:8080",  # Vue
    "http://localhost:5173",  # Vite
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# =============================================================================
# SWAGGER/OPENAPI DOCUMENTATION
# =============================================================================

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header usando el esquema Bearer. Ejemplo: "Bearer {token}"'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
    'DOC_EXPANSION': 'list',
}

# =============================================================================
# ARCHIVOS ESTÁTICOS
# =============================================================================

STATIC_URL = 'static/'

# Directorios adicionales de archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# =============================================================================
# AUTENTICACIÓN Y LOGIN
# =============================================================================

# URL de login y redirección
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'pos:venta'
LOGOUT_REDIRECT_URL = 'login'

# Configuración de sesiones
SESSION_COOKIE_AGE = 1209600  # 2 semanas
SESSION_COOKIE_SECURE = False  # True en producción con HTTPS
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# =============================================================================
# CONFIGURACIÓN DE EMAIL
# =============================================================================

# Backend de email (SMTP para producción, console para desarrollo)
# TEMPORAL: Usando console para evitar errores SMTP durante pruebas
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')

# Configuración SMTP (Gmail, SendGrid, Amazon SES, etc.)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

DEFAULT_FROM_EMAIL = 'noreply@cantinatita.com'
SERVER_EMAIL = 'server@cantinatita.com'

# =============================================================================
# CONFIGURACIÓN DE SMS
# =============================================================================

# Proveedor de SMS: 'tigo', 'personal'
SMS_PROVIDER = config('SMS_PROVIDER', default='tigo')

# Tigo Paraguay SMS
TIGO_SMS_API_KEY = config('TIGO_SMS_API_KEY', default='')
TIGO_SMS_API_URL = config('TIGO_SMS_API_URL', default='https://api.tigo.com.py/sms/send')

# Personal Paraguay SMS
PERSONAL_SMS_API_KEY = config('PERSONAL_SMS_API_KEY', default='')
PERSONAL_SMS_API_URL = config('PERSONAL_SMS_API_URL', default='https://api.personal.com.py/sms')

# =============================================================================
# CONFIGURACIÓN DE WHATSAPP
# =============================================================================

# Proveedor de WhatsApp: 'whatsapp-web-js' (GRATIS), 'business_api' (pago)
WHATSAPP_PROVIDER = config('WHATSAPP_PROVIDER', default='whatsapp-web-js')

# WhatsApp Web JS (servidor local Node.js - GRATIS)
# ⚠️ NO OFICIAL - Solo usar con número secundario
WHATSAPP_SERVER_URL = config('WHATSAPP_SERVER_URL', default='http://localhost:3000')

# WhatsApp Business API (Meta - Oficial, pago ~$0.006/msg)
WHATSAPP_ACCESS_TOKEN = config('WHATSAPP_ACCESS_TOKEN', default='')
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID', default='')

# Número de contacto de la cantina (para links wa.me)
CANTITA_WHATSAPP_CONTACTO = config('CANTITA_WHATSAPP_CONTACTO', default='+595981234567')

# =============================================================================
# GOOGLE reCAPTCHA
# =============================================================================

# Para desarrollo, usa las claves de prueba de Google:
# https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do
RECAPTCHA_PUBLIC_KEY = config('RECAPTCHA_PUBLIC_KEY', default='6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')
RECAPTCHA_PRIVATE_KEY = config('RECAPTCHA_PRIVATE_KEY', default='6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')

# Para producción, obtén tus claves en: https://www.google.com/recaptcha/admin
# RECAPTCHA_PUBLIC_KEY = config('RECAPTCHA_PUBLIC_KEY')
# RECAPTCHA_PRIVATE_KEY = config('RECAPTCHA_PRIVATE_KEY')

# Silenciar warning de claves de prueba en desarrollo
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

# =============================================================================
# CONFIGURACIÓN DE CACHE
# =============================================================================

# =============================================================================
# CONFIGURACIÓN DE CACHE (REDIS)
# =============================================================================

# TEMPORAL: Usando LocMem cache para evitar problemas de compatibilidad con Redis
# Para producción: instalar Redis y configurar correctamente
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'cantina-cache',
        'TIMEOUT': 300,  # 5 minutos
    }
}

# Comentado temporalmente - problema de compatibilidad redis-py
# try:
#     import redis
#     # Redis está disponible
#     CACHES = {
#         'default': {
#             'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#             'LOCATION': 'redis://127.0.0.1:6379/1',
#             'OPTIONS': {
#                 'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#                 'CONNECTION_POOL_KWARGS': {
#                     'max_connections': 50,
#                     'retry_on_timeout': True,
#                 },
#                 'SOCKET_CONNECT_TIMEOUT': 5,
#                 'SOCKET_TIMEOUT': 5,
#                 'IGNORE_EXCEPTIONS': True,  # No fallar si Redis no está disponible
#             },
#             'KEY_PREFIX': 'cantina',
#             'TIMEOUT': 300,  # 5 minutos por defecto
#         },
#         # Cache separado para sesiones
#         'sessions': {
#             'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#             'LOCATION': 'redis://127.0.0.1:6379/2',
#             'OPTIONS': {
#                 'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             },
#             'KEY_PREFIX': 'session',
#             'TIMEOUT': 86400,  # 24 horas
#         },
#     }
#     
#     # Usar Redis para sesiones
#     SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
#     SESSION_CACHE_ALIAS = 'sessions'
#     
# except ImportError:
#     # Redis no disponible, usar LocMem como fallback
#     CACHES = {
#         'default': {
#             'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#             'LOCATION': 'unique-snowflake',
#         }
#     }

# Cache timeout en segundos (5 minutos para dashboard)
CACHE_MIDDLEWARE_SECONDS = 300
CACHE_MIDDLEWARE_KEY_PREFIX = 'cantinatita'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CONFIGURACIÓN DE METREPAY (PAYMENT GATEWAY)
# =============================================================================
METREPAY_API_TOKEN = config('METREPAY_API_TOKEN', default='')
METREPAY_BASE_URL = config('METREPAY_BASE_URL', default='https://test.metrepay.com/api')
# =============================================================================
# CONFIGURACIÓN DE FACTURACIÓN ELECTRÓNICA (EKUATIA/SET)
# =============================================================================
# Modo: 'testing' (simulado) o 'produccion' (conectado a Ekuatia)
EKUATIA_MODO = config('EKUATIA_MODO', default='testing')
EKUATIA_API_KEY = config('EKUATIA_API_KEY', default='')
EKUATIA_BASE_URL = config('EKUATIA_BASE_URL', default='https://sifen.set.gov.py/rest/api')

# Certificados para firma digital (solo en producción)
EKUATIA_CERT_PATH = config('EKUATIA_CERT_PATH', default='')
EKUATIA_KEY_PATH = config('EKUATIA_KEY_PATH', default='')

# =============================================================================
# CONFIGURACIÓN DE IMPRESORA TÉRMICA
# =============================================================================
IMPRESORA_TIPO = config('IMPRESORA_TIPO', default='USB')  # USB, RED, BLUETOOTH
IMPRESORA_HOST = config('IMPRESORA_HOST', default='')  # Para impresora por RED
IMPRESORA_PUERTO = config('IMPRESORA_PUERTO', default='9100', cast=int)

# =============================================================================
# LOGGING MEJORADO
# =============================================================================

# Crear directorio de logs si no existe
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'cantina.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'errors.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'security.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'gestion': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Configuración de seguridad HTTPS
# NOTA: Comentadas temporalmente para pruebas con HTTP
# DESCOMENTAR cuando tengas certificado SSL instalado
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000  # 1 año
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True  # Ya está activado
# X_FRAME_OPTIONS = 'DENY'  # Ya está configurado


# Archivos estáticos para producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# =============================================================================
# CONFIGURACIÓN DE CELERY (ENERO 2026)
# =============================================================================

# URL del broker Redis para Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Configuración adicional de Celery
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Asuncion'


# =============================================================================
# CONFIGURACIÓN DE EMAILS PARA GERENCIA
# =============================================================================

# Email de gerencia para reportes diarios y notificaciones importantes
GERENCIA_EMAIL = config('GERENCIA_EMAIL', default='gerencia@cantina.edu.py')

# URL del sitio para enlaces en emails
SITE_URL = config('SITE_URL', default='http://localhost:8000')
