# Generated by Django 5.2.8 on 2026-02-09 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(db_column='id_venta', primary_key=True, serialize=False, verbose_name='ID Venta')),
                ('nro_factura_venta', models.BigIntegerField(blank=True, db_column='nro_factura_venta', null=True, verbose_name='Número de Factura')),
                ('fecha', models.DateTimeField(db_column='fecha', default=django.utils.timezone.now, verbose_name='Fecha')),
                ('monto_total', models.BigIntegerField(db_column='monto_total', verbose_name='Monto Total (Gs.)')),
                ('saldo_pendiente', models.BigIntegerField(blank=True, db_column='saldo_pendiente', null=True, verbose_name='Saldo Pendiente (Gs.)')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADA', 'Pagada')], db_column='estado_pago', default='PENDIENTE', max_length=10, verbose_name='Estado de Pago')),
                ('estado', models.CharField(choices=[('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], db_column='estado', default='PROCESADO', max_length=10, verbose_name='Estado')),
                ('tipo_venta', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], db_column='tipo_venta', max_length=20, verbose_name='Tipo de Venta')),
                ('motivo_credito', models.TextField(blank=True, db_column='motivo_credito', help_text='Justificación para la venta a crédito', null=True, verbose_name='Motivo del Crédito')),
                ('genera_factura_legal', models.BooleanField(db_column='genera_factura_legal', default=False, help_text='True si la venta genera factura contable (solo pagos con medios externos)', verbose_name='Genera Factura Legal')),
                ('autorizado_por', models.ForeignKey(blank=True, db_column='autorizado_por', help_text='Supervisor que autorizó la venta a crédito con saldo insuficiente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_pos_autorizadas', to='gestion.empleado', verbose_name='Autorizado Por')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_pos', to='gestion.cliente', verbose_name='Cliente')),
                ('id_empleado_cajero', models.ForeignKey(db_column='id_empleado_cajero', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_pos_como_cajero', to='gestion.empleado', verbose_name='Cajero')),
                ('id_hijo', models.ForeignKey(blank=True, db_column='id_hijo', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.hijo', verbose_name='Hijo')),
                ('id_tipo_pago', models.ForeignKey(db_column='id_tipo_pago', on_delete=django.db.models.deletion.PROTECT, to='gestion.tipospago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id_pago_venta', models.BigAutoField(db_column='id_pago_venta', primary_key=True, serialize=False, verbose_name='ID Pago')),
                ('monto_aplicado', models.BigIntegerField(db_column='monto_aplicado', verbose_name='Monto Aplicado (Gs.)')),
                ('referencia_transaccion', models.CharField(blank=True, db_column='referencia_transaccion', max_length=100, null=True, verbose_name='Referencia de Transacción')),
                ('fecha_pago', models.DateTimeField(db_column='fecha_pago', default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], db_column='estado', default='PROCESADO', max_length=10, verbose_name='Estado')),
                ('id_cierre', models.ForeignKey(blank=True, db_column='id_cierre', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.cierrescaja', verbose_name='Cierre de Caja')),
                ('id_medio_pago', models.ForeignKey(db_column='id_medio_pago', on_delete=django.db.models.deletion.PROTECT, to='gestion.mediospago', verbose_name='Medio de Pago')),
                ('nro_tarjeta_usada', models.ForeignKey(blank=True, db_column='nro_tarjeta_usada', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.tarjeta', verbose_name='Tarjeta Utilizada')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pos.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Venta',
                'db_table': 'pagos_venta',
                'ordering': ['-fecha_pago'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.BigAutoField(db_column='id_detalle', primary_key=True, serialize=False, verbose_name='ID Detalle')),
                ('cantidad', models.DecimalField(db_column='cantidad', decimal_places=3, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.BigIntegerField(db_column='precio_unitario', verbose_name='Precio Unitario (Gs.)')),
                ('subtotal_total', models.BigIntegerField(db_column='subtotal_total', verbose_name='Subtotal (Gs.)')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta_pos', to='gestion.producto', verbose_name='Producto')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalle_venta',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='ventas_fecha_b4b2af_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['id_cliente'], name='ventas_id_clie_fe8e32_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='ventas_estado_505824_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado_pago'], name='ventas_estado__5ceec7_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['id_venta'], name='pagos_venta_id_vent_a3048c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['fecha_pago'], name='pagos_venta_fecha_p_e3471c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['estado'], name='pagos_venta_estado_7de667_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['id_venta'], name='detalle_ven_id_vent_825723_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['id_producto'], name='detalle_ven_id_prod_904ff0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleventa',
            unique_together={('id_venta', 'id_producto')},
        ),
    ]
