# Generated by Django 5.2.8 on 2026-02-04 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(db_column='ID_Venta', primary_key=True, serialize=False, verbose_name='ID Venta')),
                ('nro_factura_venta', models.BigIntegerField(blank=True, db_column='Nro_Factura_Venta', null=True, verbose_name='Número de Factura')),
                ('fecha', models.DateTimeField(db_column='Fecha', default=django.utils.timezone.now, verbose_name='Fecha')),
                ('monto_total', models.BigIntegerField(db_column='Monto_Total', verbose_name='Monto Total (Gs.)')),
                ('saldo_pendiente', models.BigIntegerField(blank=True, db_column='Saldo_Pendiente', null=True, verbose_name='Saldo Pendiente (Gs.)')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADA', 'Pagada')], db_column='Estado_Pago', default='PENDIENTE', max_length=10, verbose_name='Estado de Pago')),
                ('estado', models.CharField(choices=[('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], db_column='Estado', default='PROCESADO', max_length=10, verbose_name='Estado')),
                ('tipo_venta', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], db_column='Tipo_Venta', max_length=20, verbose_name='Tipo de Venta')),
                ('motivo_credito', models.TextField(blank=True, db_column='Motivo_Credito', help_text='Justificación para la venta a crédito', null=True, verbose_name='Motivo del Crédito')),
                ('genera_factura_legal', models.BooleanField(db_column='Genera_Factura_Legal', default=False, help_text='True si la venta genera factura contable (solo pagos con medios externos)', verbose_name='Genera Factura Legal')),
                ('autorizado_por', models.ForeignKey(blank=True, db_column='Autorizado_Por', help_text='Supervisor que autorizó la venta a crédito con saldo insuficiente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_pos_autorizadas', to='gestion.empleado', verbose_name='Autorizado Por')),
                ('id_cliente', models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_pos', to='gestion.cliente', verbose_name='Cliente')),
                ('id_empleado_cajero', models.ForeignKey(db_column='ID_Empleado_Cajero', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_pos_como_cajero', to='gestion.empleado', verbose_name='Cajero')),
                ('id_hijo', models.ForeignKey(blank=True, db_column='ID_Hijo', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.hijo', verbose_name='Hijo')),
                ('id_tipo_pago', models.ForeignKey(db_column='ID_Tipo_Pago', on_delete=django.db.models.deletion.PROTECT, to='gestion.tipospago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id_pago_venta', models.BigAutoField(db_column='ID_Pago_Venta', primary_key=True, serialize=False, verbose_name='ID Pago')),
                ('monto_aplicado', models.BigIntegerField(db_column='Monto_Aplicado', verbose_name='Monto Aplicado (Gs.)')),
                ('referencia_transaccion', models.CharField(blank=True, db_column='Referencia_Transaccion', max_length=100, null=True, verbose_name='Referencia de Transacción')),
                ('fecha_pago', models.DateTimeField(db_column='Fecha_Pago', default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], db_column='Estado', default='PROCESADO', max_length=10, verbose_name='Estado')),
                ('id_cierre', models.ForeignKey(blank=True, db_column='ID_Cierre', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.cierrescaja', verbose_name='Cierre de Caja')),
                ('id_medio_pago', models.ForeignKey(db_column='ID_Medio_Pago', on_delete=django.db.models.deletion.PROTECT, to='gestion.mediospago', verbose_name='Medio de Pago')),
                ('nro_tarjeta_usada', models.ForeignKey(blank=True, db_column='Nro_Tarjeta_Usada', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.tarjeta', verbose_name='Tarjeta Utilizada')),
                ('id_venta', models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pos.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Venta',
                'db_table': 'pagos_venta',
                'ordering': ['-fecha_pago'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.BigAutoField(db_column='ID_Detalle', primary_key=True, serialize=False, verbose_name='ID Detalle')),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=3, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.BigIntegerField(db_column='Precio_Unitario', verbose_name='Precio Unitario (Gs.)')),
                ('subtotal_total', models.BigIntegerField(db_column='Subtotal_Total', verbose_name='Subtotal (Gs.)')),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta_pos', to='gestion.producto', verbose_name='Producto')),
                ('id_venta', models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalle_venta',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='ventas_Fecha_655cea_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['id_cliente'], name='ventas_ID_Clie_66e007_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='ventas_Estado_d18781_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado_pago'], name='ventas_Estado__0d7409_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['id_venta'], name='pagos_venta_ID_Vent_e5b764_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['fecha_pago'], name='pagos_venta_Fecha_P_2dcdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['estado'], name='pagos_venta_Estado_4aa18d_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['id_venta'], name='detalle_ven_ID_Vent_623639_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['id_producto'], name='detalle_ven_ID_Prod_5c29f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleventa',
            unique_together={('id_venta', 'id_producto')},
        ),
    ]
