# Generated by Django 5.2.8 on 2026-02-09 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionpagosventas',
            name='id_pago_venta',
            field=models.ForeignKey(db_column='ID_Pago_Venta', on_delete=django.db.models.deletion.CASCADE, to='pos.pagoventa'),
        ),
        migrations.AddField(
            model_name='aplicacionpagosventas',
            name='id_venta',
            field=models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.CASCADE, to='pos.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='autenticacion2fa',
            unique_together={('usuario', 'tipo_usuario')},
        ),
        migrations.AddField(
            model_name='autorizacionsaldonegativo',
            name='id_venta',
            field=models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.PROTECT, to='pos.venta'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_categoria_padre',
            field=models.ForeignKey(blank=True, db_column='ID_Categoria_Padre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='gestion.categoria'),
        ),
        migrations.AddField(
            model_name='categoriapromocion',
            name='id_categoria',
            field=models.ForeignKey(db_column='ID_Categoria', on_delete=django.db.models.deletion.CASCADE, related_name='promociones_categoria', to='gestion.categoria'),
        ),
        migrations.AddField(
            model_name='cierrescaja',
            name='id_caja',
            field=models.ForeignKey(db_column='ID_Caja', on_delete=django.db.models.deletion.PROTECT, to='gestion.cajas'),
        ),
        migrations.CreateModel(
            name='UsuariosWebClientes',
            fields=[
                ('id_cliente', models.OneToOneField(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usuario_web', serialize=False, to='gestion.cliente')),
                ('usuario', models.CharField(db_column='Usuario', max_length=50, unique=True)),
                ('contrasena_hash', models.CharField(db_column='Contrasena_Hash', max_length=128)),
                ('ultimo_acceso', models.DateTimeField(blank=True, db_column='Ultimo_Acceso', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Usuario Web Cliente',
                'verbose_name_plural': 'Usuarios Web Clientes',
                'db_table': 'usuarios_web_clientes',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cargassaldo',
            name='id_cliente_origen',
            field=models.ForeignKey(blank=True, db_column='ID_Cliente_Origen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas_origen', to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='autorizacionsaldonegativo',
            name='id_cliente',
            field=models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.PROTECT, to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='auditoriausuariosweb',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='ID_Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_web', to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='aplicacionpagoscompras',
            name='id_compra',
            field=models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.CASCADE, to='gestion.compras'),
        ),
        migrations.AddField(
            model_name='conciliacionpagos',
            name='id_pago_venta',
            field=models.OneToOneField(db_column='ID_Pago_Venta', on_delete=django.db.models.deletion.CASCADE, to='pos.pagoventa'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacionessistema',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costoshistoricos',
            name='id_compra',
            field=models.ForeignKey(blank=True, db_column='ID_Compra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.compras'),
        ),
        migrations.CreateModel(
            name='DatosFacturacionElect',
            fields=[
                ('id_documento', models.OneToOneField(db_column='ID_Documento', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion.documentostributarios')),
                ('cdc', models.CharField(db_column='CDC', max_length=44, unique=True)),
                ('url_kude', models.CharField(blank=True, db_column='URL_KuDE', max_length=255, null=True)),
                ('xml_transmitido', models.TextField(blank=True, db_column='XML_Transmitido', null=True)),
                ('estado_sifen', models.CharField(blank=True, db_column='Estado_SIFEN', max_length=9, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, db_column='Fecha_Envio', null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, db_column='Fecha_Respuesta', null=True)),
            ],
            options={
                'verbose_name': 'Datos Facturación Electrónica',
                'verbose_name_plural': 'Datos Facturación Electrónica',
                'db_table': 'datos_facturacion_elect',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatosFacturacionFisica',
            fields=[
                ('id_documento', models.OneToOneField(db_column='ID_Documento', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion.documentostributarios')),
                ('nro_preimpreso_interno', models.CharField(db_column='Nro_Preimpreso_Interno', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Datos Facturación Física',
                'verbose_name_plural': 'Datos Facturación Física',
                'db_table': 'datos_facturacion_fisica',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='id_ajuste',
            field=models.ForeignKey(db_column='ID_Ajuste', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.ajustesinventario'),
        ),
        migrations.AddField(
            model_name='detallecomisionventa',
            name='id_pago_venta',
            field=models.ForeignKey(db_column='ID_Pago_Venta', on_delete=django.db.models.deletion.CASCADE, to='pos.pagoventa'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='id_compra',
            field=models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.compras'),
        ),
        migrations.AddField(
            model_name='consumotarjeta',
            name='id_empleado_registro',
            field=models.ForeignKey(blank=True, db_column='ID_Empleado_Registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_registrados', to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='cierrescaja',
            name='id_empleado',
            field=models.ForeignKey(db_column='ID_Empleado', on_delete=django.db.models.deletion.PROTECT, to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='autorizacionsaldonegativo',
            name='id_empleado_autoriza',
            field=models.ForeignKey(db_column='ID_Empleado_Autoriza', on_delete=django.db.models.deletion.PROTECT, to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='auditoriaempleados',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='ID_Empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='auditoriacomisiones',
            name='id_empleado_modifico',
            field=models.ForeignKey(blank=True, db_column='ID_Empleado_Modifico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='ajustesinventario',
            name='id_empleado_responsable',
            field=models.ForeignKey(db_column='ID_Empleado_Responsable', on_delete=django.db.models.deletion.PROTECT, to='gestion.empleado'),
        ),
        migrations.CreateModel(
            name='VistaConsumosEstudiante',
            fields=[
                ('id_hijo', models.OneToOneField(db_column='ID_Hijo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='consumos_vista', serialize=False, to='gestion.hijo')),
                ('estudiante', models.CharField(db_column='Estudiante', max_length=202)),
                ('responsable_nombre', models.CharField(db_column='Responsable_Nombre', max_length=100)),
                ('responsable_apellido', models.CharField(db_column='Responsable_Apellido', max_length=100)),
                ('nro_tarjeta', models.CharField(db_column='Nro_Tarjeta', max_length=20)),
                ('saldo_actual', models.BigIntegerField(db_column='Saldo_Actual')),
                ('total_consumos', models.BigIntegerField(db_column='Total_Consumos')),
                ('total_consumido', models.DecimalField(db_column='Total_Consumido', decimal_places=2, max_digits=32)),
                ('ultimo_consumo', models.DateTimeField(db_column='Ultimo_Consumo')),
                ('total_recargas', models.BigIntegerField(db_column='Total_Recargas')),
                ('total_recargado', models.DecimalField(db_column='Total_Recargado', decimal_places=2, max_digits=32)),
            ],
            options={
                'verbose_name': 'Vista: Consumos por Hijo',
                'verbose_name_plural': 'Vista: Consumos por Hijo',
                'db_table': 'v_consumos_estudiante',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hijo',
            name='id_cliente_responsable',
            field=models.ForeignKey(db_column='ID_Cliente_Responsable', on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='cuentaalmuerzomensual',
            name='id_hijo',
            field=models.ForeignKey(db_column='ID_Hijo', on_delete=django.db.models.deletion.PROTECT, to='gestion.hijo'),
        ),
        migrations.AddField(
            model_name='historialgradohijo',
            name='id_hijo',
            field=models.ForeignKey(db_column='ID_Hijo', on_delete=django.db.models.deletion.CASCADE, related_name='historial_grados', to='gestion.hijo'),
        ),
        migrations.AddField(
            model_name='historicoprecios',
            name='id_empleado_autoriza',
            field=models.ForeignKey(blank=True, db_column='ID_Empleado_Autoriza', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_lista',
            field=models.ForeignKey(db_column='ID_Lista', on_delete=django.db.models.deletion.PROTECT, to='gestion.listaprecios'),
        ),
        migrations.AddField(
            model_name='movimientosstock',
            name='id_compra',
            field=models.ForeignKey(blank=True, db_column='ID_Compra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.compras'),
        ),
        migrations.AddField(
            model_name='movimientosstock',
            name='id_empleado_autoriza',
            field=models.ForeignKey(db_column='ID_Empleado_Autoriza', on_delete=django.db.models.deletion.PROTECT, to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='movimientosstock',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='ID_Venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.venta'),
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='id_movimientostock',
            field=models.OneToOneField(db_column='ID_MovimientoStock', on_delete=django.db.models.deletion.CASCADE, to='gestion.movimientosstock'),
        ),
        migrations.AddField(
            model_name='notascreditocliente',
            name='id_cliente',
            field=models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.PROTECT, to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='notascreditocliente',
            name='id_empleado_autoriza',
            field=models.ForeignKey(db_column='ID_Empleado_Autoriza', on_delete=django.db.models.deletion.PROTECT, to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='notascreditocliente',
            name='id_venta_origen',
            field=models.ForeignKey(blank=True, db_column='ID_Venta_Origen', null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.venta'),
        ),
        migrations.AddField(
            model_name='detallenota',
            name='id_nota',
            field=models.ForeignKey(db_column='ID_Nota', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.notascreditocliente'),
        ),
        migrations.AddField(
            model_name='cargassaldo',
            name='id_nota',
            field=models.ForeignKey(blank=True, db_column='ID_Nota', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.notascreditocliente'),
        ),
        migrations.AddField(
            model_name='notascreditoproveedor',
            name='id_compra_original',
            field=models.ForeignKey(blank=True, db_column='ID_Compra_Original', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.compras'),
        ),
        migrations.AddField(
            model_name='detallenotacreditoproveedor',
            name='id_nota_proveedor',
            field=models.ForeignKey(db_column='ID_Nota_Proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.notascreditoproveedor'),
        ),
        migrations.AddField(
            model_name='notificacionsistema',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagocuentaalmuerzo',
            name='id_cuenta',
            field=models.ForeignKey(db_column='ID_Cuenta', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='gestion.cuentaalmuerzomensual'),
        ),
        migrations.AddField(
            model_name='pagocuentaalmuerzo',
            name='id_empleado_registro',
            field=models.ForeignKey(blank=True, db_column='ID_Empleado_Registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='pagosalmuerzomensual',
            name='id_venta',
            field=models.OneToOneField(blank=True, db_column='ID_Venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.venta'),
        ),
        migrations.AddField(
            model_name='pagosproveedores',
            name='id_compra',
            field=models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='gestion.compras'),
        ),
        migrations.AddField(
            model_name='pagosproveedores',
            name='id_medio_pago',
            field=models.ForeignKey(db_column='ID_Medio_Pago', on_delete=django.db.models.deletion.PROTECT, to='gestion.mediospago'),
        ),
        migrations.AddField(
            model_name='aplicacionpagoscompras',
            name='id_pago_proveedor',
            field=models.ForeignKey(db_column='ID_Pago_Proveedor', on_delete=django.db.models.deletion.CASCADE, to='gestion.pagosproveedores'),
        ),
        migrations.AddField(
            model_name='preciosporlista',
            name='id_lista_precios',
            field=models.ForeignKey(db_column='ID_Lista', on_delete=django.db.models.deletion.CASCADE, related_name='precios_productos', to='gestion.listaprecios'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(db_column='ID_Categoria', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='gestion.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_impuesto',
            field=models.ForeignKey(db_column='ID_Impuesto', on_delete=django.db.models.deletion.PROTECT, to='gestion.impuesto'),
        ),
        migrations.AddField(
            model_name='preciosporlista',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='precios_lista', to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='movimientosstock',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='historicoprecios',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='historico_precios', to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='detallenotacreditoproveedor',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.PROTECT, to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='detallenota',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.PROTECT, to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.PROTECT, to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.PROTECT, to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='costoshistoricos',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='costos_historicos', to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='productoalergeno',
            name='id_alergeno',
            field=models.ForeignKey(db_column='ID_Alergeno', on_delete=django.db.models.deletion.CASCADE, related_name='productos_con_alergeno', to='gestion.alergeno'),
        ),
        migrations.AddField(
            model_name='productoalergeno',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='alergenos_producto', to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='productopromocion',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='promociones_producto', to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='productopromocion',
            name='id_promocion',
            field=models.ForeignKey(db_column='ID_Promocion', on_delete=django.db.models.deletion.CASCADE, related_name='productos_promocion', to='gestion.promocion'),
        ),
        migrations.AddField(
            model_name='categoriapromocion',
            name='id_promocion',
            field=models.ForeignKey(db_column='ID_Promocion', on_delete=django.db.models.deletion.CASCADE, related_name='categorias_promocion', to='gestion.promocion'),
        ),
        migrations.AddField(
            model_name='promocionaplicada',
            name='id_promocion',
            field=models.ForeignKey(db_column='ID_Promocion', on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='gestion.promocion'),
        ),
        migrations.AddField(
            model_name='promocionaplicada',
            name='id_venta',
            field=models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.CASCADE, related_name='promociones_aplicadas', to='pos.venta'),
        ),
        migrations.AddField(
            model_name='notascreditoproveedor',
            name='id_proveedor',
            field=models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='gestion.proveedor'),
        ),
        migrations.AddField(
            model_name='compras',
            name='id_proveedor',
            field=models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='gestion.proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='puntosexpedicion',
            unique_together={('codigo_establecimiento', 'codigo_punto_expedicion')},
        ),
        migrations.AddField(
            model_name='registroconsumoalmuerzo',
            name='id_hijo',
            field=models.ForeignKey(db_column='ID_Hijo', on_delete=django.db.models.deletion.PROTECT, to='gestion.hijo'),
        ),
        migrations.AddField(
            model_name='restriccioneshijos',
            name='id_hijo',
            field=models.ForeignKey(db_column='ID_Hijo', on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='gestion.hijo'),
        ),
        migrations.AddField(
            model_name='solicitudesnotificacion',
            name='id_cliente',
            field=models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='stockunico',
            name='id_producto',
            field=models.OneToOneField(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='suscripcionesalmuerzo',
            name='id_hijo',
            field=models.ForeignKey(db_column='ID_Hijo', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='gestion.hijo'),
        ),
        migrations.AddField(
            model_name='suscripcionesalmuerzo',
            name='id_plan_almuerzo',
            field=models.ForeignKey(db_column='ID_Plan_Almuerzo', on_delete=django.db.models.deletion.PROTECT, to='gestion.planesalmuerzo'),
        ),
        migrations.AddField(
            model_name='pagosalmuerzomensual',
            name='id_suscripcion',
            field=models.ForeignKey(db_column='ID_Suscripcion', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='gestion.suscripcionesalmuerzo'),
        ),
        migrations.AddField(
            model_name='tarifascomision',
            name='id_medio_pago',
            field=models.ForeignKey(db_column='ID_Medio_Pago', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='gestion.mediospago'),
        ),
        migrations.AddField(
            model_name='detallecomisionventa',
            name='id_tarifa',
            field=models.ForeignKey(db_column='ID_Tarifa', on_delete=django.db.models.deletion.PROTECT, to='gestion.tarifascomision'),
        ),
        migrations.AddField(
            model_name='auditoriacomisiones',
            name='id_tarifa',
            field=models.ForeignKey(blank=True, db_column='ID_Tarifa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.tarifascomision'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_hijo',
            field=models.OneToOneField(db_column='ID_Hijo', on_delete=django.db.models.deletion.PROTECT, to='gestion.hijo'),
        ),
        migrations.AddField(
            model_name='solicitudesnotificacion',
            name='nro_tarjeta',
            field=models.ForeignKey(db_column='Nro_Tarjeta', on_delete=django.db.models.deletion.CASCADE, to='gestion.tarjeta'),
        ),
        migrations.AddField(
            model_name='registroconsumoalmuerzo',
            name='nro_tarjeta',
            field=models.ForeignKey(blank=True, db_column='Nro_Tarjeta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_almuerzo', to='gestion.tarjeta'),
        ),
        migrations.AddField(
            model_name='notificacionsaldo',
            name='nro_tarjeta',
            field=models.ForeignKey(db_column='nro_tarjeta', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_saldo', to='gestion.tarjeta'),
        ),
        migrations.AddField(
            model_name='consumotarjeta',
            name='nro_tarjeta',
            field=models.ForeignKey(db_column='Nro_Tarjeta', on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='gestion.tarjeta'),
        ),
        migrations.AddField(
            model_name='cargassaldo',
            name='nro_tarjeta',
            field=models.ForeignKey(db_column='Nro_Tarjeta', on_delete=django.db.models.deletion.PROTECT, to='gestion.tarjeta'),
        ),
        migrations.AddField(
            model_name='tarjetaautorizacion',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='ID_Empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.empleado'),
        ),
        migrations.AddField(
            model_name='logautorizacion',
            name='id_tarjeta_autorizacion',
            field=models.ForeignKey(db_column='ID_Tarjeta_Autorizacion', on_delete=django.db.models.deletion.CASCADE, to='gestion.tarjetaautorizacion'),
        ),
        migrations.AddField(
            model_name='timbrados',
            name='id_punto',
            field=models.ForeignKey(db_column='ID_Punto', on_delete=django.db.models.deletion.PROTECT, to='gestion.puntosexpedicion'),
        ),
        migrations.AddField(
            model_name='documentostributarios',
            name='nro_timbrado',
            field=models.ForeignKey(db_column='Nro_Timbrado', on_delete=django.db.models.deletion.PROTECT, to='gestion.timbrados'),
        ),
        migrations.AddField(
            model_name='registroconsumoalmuerzo',
            name='id_tipo_almuerzo',
            field=models.ForeignKey(blank=True, db_column='ID_Tipo_Almuerzo', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.tipoalmuerzo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_cliente',
            field=models.ForeignKey(db_column='ID_Tipo_Cliente', on_delete=django.db.models.deletion.PROTECT, to='gestion.tipocliente'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(db_column='ID_Rol', on_delete=django.db.models.deletion.PROTECT, to='gestion.tiporolgeneral'),
        ),
        migrations.AddField(
            model_name='tokenrecuperacion',
            name='id_cliente',
            field=models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='transacciononline',
            name='nro_tarjeta',
            field=models.ForeignKey(blank=True, db_column='Nro_Tarjeta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_online', to='gestion.tarjeta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_unidad_medida',
            field=models.ForeignKey(blank=True, db_column='ID_Unidad_de_Medida', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.unidadmedida'),
        ),
        migrations.AddField(
            model_name='usuarioportal',
            name='cliente',
            field=models.OneToOneField(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_portal', to='gestion.cliente'),
        ),
        migrations.AddField(
            model_name='transacciononline',
            name='usuario_portal',
            field=models.ForeignKey(blank=True, db_column='ID_Usuario_Portal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='gestion.usuarioportal'),
        ),
        migrations.AddField(
            model_name='tokenverificacion',
            name='usuario_portal',
            field=models.ForeignKey(db_column='ID_Usuario_Portal', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='gestion.usuarioportal'),
        ),
        migrations.AddField(
            model_name='preferencianotificacion',
            name='usuario_portal',
            field=models.ForeignKey(db_column='ID_Usuario_Portal', on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to='gestion.usuarioportal'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario_portal',
            field=models.ForeignKey(db_column='ID_Usuario_Portal', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion.usuarioportal'),
        ),
        migrations.AddField(
            model_name='vistarecargashistorial',
            name='id_hijo',
            field=models.ForeignKey(db_column='ID_Hijo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recargas_vista', to='gestion.hijo'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentaalmuerzomensual',
            unique_together={('id_hijo', 'anio', 'mes')},
        ),
        migrations.AddIndex(
            model_name='notificacionsistema',
            index=models.Index(fields=['usuario', '-creada_en'], name='gestion_not_usuario_992fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionsistema',
            index=models.Index(fields=['usuario', 'leida'], name='gestion_not_usuario_537bae_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionsistema',
            index=models.Index(fields=['tipo', '-creada_en'], name='gestion_not_tipo_425520_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preciosporlista',
            unique_together={('id_producto', 'id_lista_precios')},
        ),
        migrations.AlterUniqueTogether(
            name='detallecompra',
            unique_together={('id_compra', 'id_producto')},
        ),
        migrations.AlterUniqueTogether(
            name='detalleajuste',
            unique_together={('id_ajuste', 'id_producto')},
        ),
        migrations.AlterUniqueTogether(
            name='productoalergeno',
            unique_together={('id_producto', 'id_alergeno')},
        ),
        migrations.AlterUniqueTogether(
            name='productopromocion',
            unique_together={('id_promocion', 'id_producto')},
        ),
        migrations.AlterUniqueTogether(
            name='categoriapromocion',
            unique_together={('id_promocion', 'id_categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='suscripcionesalmuerzo',
            unique_together={('id_hijo', 'id_plan_almuerzo', 'estado')},
        ),
        migrations.AlterUniqueTogether(
            name='pagosalmuerzomensual',
            unique_together={('id_suscripcion', 'mes_pagado')},
        ),
        migrations.AddIndex(
            model_name='notificacionsaldo',
            index=models.Index(fields=['nro_tarjeta', 'tipo_notificacion'], name='idx_tarjeta_tipo_not'),
        ),
        migrations.AddIndex(
            model_name='notificacionsaldo',
            index=models.Index(fields=['leida'], name='idx_leida_not'),
        ),
        migrations.AddIndex(
            model_name='notificacionsaldo',
            index=models.Index(fields=['fecha_creacion'], name='idx_fecha_creacion_not'),
        ),
        migrations.AlterUniqueTogether(
            name='documentostributarios',
            unique_together={('nro_timbrado', 'nro_secuencial')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['descripcion'], name='productos_Descrip_8ec57a_idx'),
        ),
        migrations.AddConstraint(
            model_name='preferencianotificacion',
            constraint=models.UniqueConstraint(fields=('usuario_portal', 'tipo_notificacion'), name='unique_usuario_tipo'),
        ),
    ]
